// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var photoHTML;
    photoHTML = (function(_this) {
      return function(photo) {
        return "<li> <a id='photo_" + photo.id + "' href='" + photo.url + "'> <img src='" + photo.url + "' alt='" + photo.alt + "' /> </a> </li>";
      };
    })(this);
    return $.ajax({
      url: '/photos',
      type: 'GET',
      contentType: 'application/json',
      onSuccess: (function(_this) {
        return function(response) {
          var node, photo, _i, _len, _ref, _results;
          _ref = response.photos;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            photo = _ref[_i];
            node = $(photoHTML(photo)).appendTo($("#photos-list"));
            _results.push(node.on('click', function(e) {
              e.preventDefault();
              return node.find('img').prop('src', photo.url + '.grayscaled.jpg');
            }));
          }
          return _results;
        };
      })(this),
      onFailure: (function(_this) {
        return function() {
          return $("#photo-list").append("<li> Failed to fetch photos. </li>");
        };
      })(this)
    });
  });

}).call(this);
